### ISSUE TITLE
question

### ISSUE THREAD

**Issue by firmianay** [actuator/com.cutestudio.colordialer#1]
Hello, I have a question about this vulnerability. As a dialer, isn't it normal to provide the function of making calls to other programs? Should the user confirm before making a call? How does the default dialer do it?

**Comment by actuator** [comment]
Hi,

We've identified a security concern in the Android app. Specifically,
there's an exported activity that allows any app, even those without phone
permissions, to place phone calls without user interaction. This poses a
risk as there's no confirmation step before the call is made.

Typically, apps follow one of two approaches:

1. Restrict the invocation of such activities to only those apps that
possess the required permissions.
2. Allow the dialpad to show the intended number but necessitate an extra
user action, like a button press, to place the call.

To address this, the simplest solution would be to set the "exported"
attribute of the activity in question to "false." This change would prevent
unauthorized apps from accessing and triggering it.

Thanks

---

**Comment by firmianay** [comment]
Thank you for your answer. Has this vulnerability been fixed?

**Comment by actuator** [comment]
This remains unpatched as of ver. 2.2.1.

This is however an easy fix just change the impacted activity exported
status from 'true' to 'false'.

Thanks
